### ISSUE TITLE
Error: spawn jekyll.bat ENOENT

### ISSUE THREAD

**Issue by vanshika0109** [j143/systemds-website#3]
**Problem:**
I am trying to run gulp command on the PowerShell, but this error is prompting every time I try to execute it.
Could anyone help to resolve this?

Screenshot:
![image](https://user-images.githubusercontent.com/57085458/87411811-dd58fa00-c5e5-11ea-9c77-2ad54e3c8d29.png)

**Causes:**
More info at https://github.com/j143/systemds-website/issues/3#issuecomment-658130013

**Solution:**
1. https://github.com/j143/systemds-website/issues/3#issuecomment-658132186
2. https://github.com/j143/systemds-website/issues/3#issuecomment-658279233
3. https://github.com/j143/systemds-website/issues/3#issuecomment-660594707

**Comment by j143** [comment]
Hi @rebeccadias - Can you provide help here?. Thank you.

**Comment by rebeccadias** [comment]
Yes sure .Thank You

**Comment by j143** [comment]
> Windows platform

**Some background:**
1. Corresponding to on windows (`'win32'`), `jekyll.bat` should be utilized.
https://github.com/j143/systemds-website/blob/7c9284a4655f25cc78dc8ab390f58292c927afbb/gulpfile.js#L9

2. Check the `process.platform` as shown.
![image](https://user-images.githubusercontent.com/53068787/87420153-5fe7b680-c5f2-11ea-883d-8646a35925f5.png)

3. Based on 1, `jekyll.bat` should be available on the path.

Links related to this issue:
https://stackoverflow.com/questions/21856861/running-jekyll-as-a-child-process-in-gulp-node

> Linux platform 

Links related to this issue:
https://github.com/willianjusten/cards-jekyll-template/issues/20

**Comment by j143** [comment]
Hi @vanshika0109 - can you see the above comment. This might give you an idea of how `gulp` command is invoking `jekyll`.

**Comment by rebeccadias** [comment]
@vanshika0109 -
Hi,
For windows 
1.Make sure you have Ruby Installed. If not install it from here https://rubyinstaller.org 
2.set up the ruby environment in the Path variables .
![image](https://user-images.githubusercontent.com/56188657/87421528-b229d700-c5f4-11ea-910c-4c1dcfe5c3ca.png)
 
3.Install jekyll with the help of this https://jekyllrb.com/docs/

**Comment by vanshika0109** [comment]
> Hi @vanshika0109 - can you see the above comment. This might give you an idea of how `gulp` command is invoking `jekyll`.

Yes, I can see it and I understand that😊.

**Comment by vanshika0109** [comment]
I have installed ruby but now I am not able to install jekyll.
I have set the path also.
![image](https://user-images.githubusercontent.com/57085458/87438093-ba8e0c00-c60c-11ea-94f1-70f551b413e9.png)

**Comment by j143** [comment]
Make sure you could spot jekyll.bat file in your installation.

Please, take walk for while and spend reading each comment for 5 minutes.

**Comment by rebeccadias** [comment]
I guess it is the RubyGems version incompatibility with native extension gems. 
https://stackoverflow.com/questions/26276207/error-failed-to-build-gem-native-extension-on-windows
https://github.com/jekyll/jekyll/issues/7000

**Comment by j143** [comment]
Hi @vanshika0109 - If you solved this issue please let others know. (may be you would want to thank the people for their interest in solving this issue.)

Thank you. 😃

**Comment by vanshika0109** [comment]
I am really sorry for the delay. I have solved the issue. The solutions you all provided helped me a lot. Thank you so much, both of you😊.

**Comment by vanshika0109** [comment]
I solved this error by running the command 'gem install jekyll'. The only reason why jekyll was not working was that it wasn't getting installed properly, this happened more than 2 times. After running this command I used the 'gulp' command again and it worked successfully. 😃

![image](https://user-images.githubusercontent.com/57085458/87868593-34c7e300-c9b5-11ea-9238-762afa8fadc8.png)
